spring.application.name=mod05proyMvcSpringBoot
# THYMELEAF
spring.thymeleaf.check-template-location=false
# CONEXION BD
spring.datasource.url=jdbc:mysql://localhost:3306/ejemplosjdbc?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
# LOGGING
logging.level.root=WARN
#logging.level.org.springframework.boot=DEBUG
logging.level.mx.com.qtx=INFO
logging.level.org.springframework.boot.tomcat=INFO
# BANNER SPRING
spring.main.banner-mode=off
# SERVER
#server.port=8082
#server.servlet.context-path=/AppEjemplo
#
#debug=true
# PROPIEDADES PERSONALIZADAS DE APLICACION
qtx.com.logpersona.tipo=consola
#qtx.com.saludo=Hola Hector
#
#qtx.com.logpersona.tipo=archivo
#qtx.com.logpersona.formato=json
#qtx.com.logpersona.formato=txt