spring.application.name=mod05proyMvcSpringBoot
# THYMELEAF
spring.thymeleaf.check-template-location=false
#
# I18n
# spring.messages.use-code-as-default-message=false
# Basenames separados por coma. No es necesario el prefijo classpath:
#spring.messages.basename=textosTorneo,msgValidacion
#
# CONEXION BD ANTERIOR: Cuando mi app usaba solo una BD
#spring.datasource.url=jdbc:mysql://localhost:3306/ejemplosjdbc?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root
#
# CONEXION BD
spring.datasource.negocio.url=jdbc:mysql://localhost:3306/ejemplosjdbc?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.negocio.username=root
spring.datasource.negocio.password=root
spring.datasource.negocio.driver-class-name=com.mysql.cj.jdbc.Driver
# CONEXION BD SEGURIDAD
spring.datasource.security.url=jdbc:mysql://localhost:3306/bdUsuarios?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.security.username=root
spring.datasource.security.password=root
spring.datasource.security.driver-class-name=com.mysql.cj.jdbc.Driver
#
# LOGGING
logging.level.root=WARN
#logging.level.org.springframework.boot=DEBUG
logging.level.mx.com.qtx=INFO
logging.level.org.springframework.boot.tomcat=INFO
logging.level.org.springframework.security=debug

# BANNER SPRING
spring.main.banner-mode=off
# SERVER
#server.port=8082
#server.servlet.context-path=/AppEjemplo
#
#debug=true
# usuarios
#spring.security.user.name=alex
#spring.security.user.password=cochabamba
#spring.security.user.name=vini
#spring.security.user.password=bombastico

#
# PROPIEDADES PERSONALIZADAS DE APLICACION
qtx.com.logpersona.tipo=consola
#qtx.com.saludo=Hola Hector
#
#qtx.com.logpersona.tipo=archivo
#qtx.com.logpersona.formato=json
#qtx.com.logpersona.formato=txt